dist: xenial
language: nodejs
nodejs: '8'

before_install: npm set repository "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN"
install: npm install
before_script: npm run build
script: npm run test:codacy